// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1rEoca7F_zj2xN8zJOKUVtDjqlhVu3n4',
    appId: '1:989549334771:web:e5fa172bc2c5bd47e92786',
    messagingSenderId: '989549334771',
    projectId: 'mamma-magic-e31f7',
    authDomain: 'mamma-magic-e31f7.firebaseapp.com',
    storageBucket: 'mamma-magic-e31f7.appspot.com',
    measurementId: 'G-DKSCNJHGRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRx58irnDjDTlDhikXq5zmx2mq170YNEk',
    appId: '1:989549334771:android:35122c154ae78f92e92786',
    messagingSenderId: '989549334771',
    projectId: 'mamma-magic-e31f7',
    storageBucket: 'mamma-magic-e31f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8cmgGMm6o-Qa01sRdbXM_4zVTL0vLxbE',
    appId: '1:989549334771:ios:f22c204d06c9318be92786',
    messagingSenderId: '989549334771',
    projectId: 'mamma-magic-e31f7',
    storageBucket: 'mamma-magic-e31f7.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8cmgGMm6o-Qa01sRdbXM_4zVTL0vLxbE',
    appId: '1:989549334771:ios:f22c204d06c9318be92786',
    messagingSenderId: '989549334771',
    projectId: 'mamma-magic-e31f7',
    storageBucket: 'mamma-magic-e31f7.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1rEoca7F_zj2xN8zJOKUVtDjqlhVu3n4',
    appId: '1:989549334771:web:8da5517dc8ad013de92786',
    messagingSenderId: '989549334771',
    projectId: 'mamma-magic-e31f7',
    authDomain: 'mamma-magic-e31f7.firebaseapp.com',
    storageBucket: 'mamma-magic-e31f7.appspot.com',
    measurementId: 'G-RZPK959RF3',
  );
}
